// Shared StyleSheets. `s` is the app-wide sheet; cal/co/ms/dst are scoped to the
// calendar, checkout, menu/2FA, and date-strip respectively.
import { StyleSheet, Platform } from 'react-native';
import { BRAND, BRAND_LT, GRAY_50, GRAY_100, GRAY_200, GRAY_400, GRAY_500, GRAY_700, GRAY_900 } from './theme';

export const s = StyleSheet.create({
  screen:          { flex:1, backgroundColor:'#fff' },
  center:          { flex:1, alignItems:'center', justifyContent:'center' },
  header:          { flexDirection:'row', alignItems:'center', paddingHorizontal:20, paddingVertical:14, borderBottomWidth:1, borderBottomColor:GRAY_100, backgroundColor:'#fff' },
  headerTitle:     { fontSize:17, fontWeight:'700', color:GRAY_900, flex:1 },
  listContent:     { padding:16 },
  sectionLabel:    { fontSize:11, fontWeight:'700', color:GRAY_400, textTransform:'uppercase', letterSpacing:0.8, marginBottom:8, marginTop:4 },
  emptyText:       { color:GRAY_400, fontSize:14, textAlign:'center', marginTop:20 },
  row:             { flexDirection:'row', alignItems:'center', gap:8 },
  card:            { backgroundColor:'#fff', borderRadius:14, borderWidth:1, borderColor:GRAY_100, padding:14, marginBottom:10, flexDirection:'row', alignItems:'center', gap:12, shadowColor:'#000', shadowOpacity:0.04, shadowRadius:4, shadowOffset:{width:0,height:1}, elevation:1 },
  cardLeft:        { width:16, alignItems:'center' },
  cardBody:        { flex:1 },
  dot:             { width:10, height:10, borderRadius:5 },
  clientName:      { fontSize:14, fontWeight:'600', color:GRAY_900 },
  sub:             { fontSize:12, color:GRAY_500, marginTop:2 },
  dateText:        { fontSize:12, color:BRAND, fontWeight:'500', marginTop:3 },
  price:           { fontSize:13, fontWeight:'700', color:GRAY_700 },
  pill:            { paddingHorizontal:8, paddingVertical:3, borderRadius:99, borderWidth:1 },
  pillText:        { fontSize:10, fontWeight:'700', textTransform:'uppercase', letterSpacing:0.5 },
  verifiedPill:    { flexDirection:'row', alignItems:'center', gap:3, backgroundColor:'#6D5BD0', borderRadius:99, paddingHorizontal:7, paddingVertical:2 },
  verifiedPillText:{ fontSize:10, fontWeight:'700', color:'#fff' },
  // Detail sheet
  overlay:         { position:'absolute', top:0, left:0, right:0, bottom:0, backgroundColor:'rgba(0,0,0,0.4)', justifyContent:'flex-end', zIndex:99 },
  sheet:           { backgroundColor:'#fff', borderTopLeftRadius:20, borderTopRightRadius:20, padding:20, paddingBottom:Platform.OS==='ios'?34:20, maxHeight:'90%' },
  sheetHandle:     { width:40, height:4, backgroundColor:GRAY_200, borderRadius:99, alignSelf:'center', marginBottom:16 },
  sheetTitle:      { fontSize:18, fontWeight:'700', color:GRAY_900, marginBottom:16 },
  aptBlock:        { borderLeftWidth:3, paddingLeft:12, marginBottom:16 },
  aptBlockDate:    { fontSize:14, fontWeight:'600', color:GRAY_900 },
  aptBlockSub:     { fontSize:13, color:GRAY_500, marginTop:2 },
  detailRow:       { flexDirection:'row', justifyContent:'space-between', paddingVertical:7, borderBottomWidth:1, borderBottomColor:GRAY_100 },
  detailLabel:     { fontSize:13, color:GRAY_400 },
  detailValue:     { fontSize:13, fontWeight:'600', color:GRAY_900 },
  notesBox:        { backgroundColor:GRAY_50, borderRadius:10, padding:12, marginTop:12 },
  notesText:       { fontSize:13, color:GRAY_700 },
  sheetActions:    { gap:8, marginTop:20 },
  btnPrimary:      { backgroundColor:BRAND, borderRadius:12, padding:14, alignItems:'center' },
  btnPrimaryText:  { color:'#fff', fontWeight:'700', fontSize:15 },
  btnSecondary:    { backgroundColor:GRAY_100, borderRadius:12, padding:14, alignItems:'center' },
  btnSecondaryText:{ color:GRAY_700, fontWeight:'600', fontSize:15 },
  btnDanger:       { backgroundColor:'#FEF2F2', borderRadius:12, borderWidth:1, borderColor:'#FCA5A5', padding:14, alignItems:'center' },
  btnDangerText:   { color:'#DC2626', fontWeight:'600', fontSize:15 },
  btnGhost:        { borderRadius:12, padding:12, alignItems:'center' },
  btnGhostText:    { color:GRAY_500, fontSize:14 },
  // Book
  stepLabel:       { fontSize:16, fontWeight:'700', color:GRAY_900, marginBottom:6 },
  backBtn:         { marginBottom:12 },
  backText:        { color:BRAND, fontSize:14, fontWeight:'500' },
  svcDot:          { width:12, height:12, borderRadius:99, marginRight:4 },
  avatar:          { width:40, height:40, borderRadius:20, backgroundColor:BRAND_LT, alignItems:'center', justifyContent:'center' },
  avatarImg:       { width:40, height:40, borderRadius:20, backgroundColor:GRAY_100 },
  avatarText:      { color:BRAND, fontWeight:'700', fontSize:13 },
  bizLogoImg:      { width:44, height:44, borderRadius:12, backgroundColor:GRAY_100 },
  checkbox:        { width:20, height:20, borderRadius:10, borderWidth:2, borderColor:GRAY_200, alignItems:'center', justifyContent:'center', marginLeft:8 },
  checkboxActive:  { borderColor:BRAND, backgroundColor:BRAND },
  cartBar:         { backgroundColor:BRAND_LT, borderRadius:12, padding:12, marginTop:8, alignItems:'center' },
  cartText:        { color:BRAND, fontWeight:'700', fontSize:14 },
  datePill:        { width:52, marginRight:8, borderRadius:12, borderWidth:1, borderColor:GRAY_200, backgroundColor:'#fff', paddingVertical:10, alignItems:'center' },
  datePillActive:  { backgroundColor:BRAND, borderColor:BRAND },
  datePillDay:     { fontSize:11, color:GRAY_500, fontWeight:'600' },
  datePillNum:     { fontSize:17, fontWeight:'700', color:GRAY_900, marginTop:2 },
  slotGrid:        { flexDirection:'row', flexWrap:'wrap', gap:10, marginTop:8 },
  slotBtn:         { borderWidth:1, borderColor:GRAY_200, borderRadius:10, paddingVertical:10, paddingHorizontal:14, backgroundColor:'#fff' },
  slotBtnActive:   { borderColor:BRAND, backgroundColor:BRAND_LT },
  slotText:        { color:GRAY_700, fontSize:13, fontWeight:'500' },
  slotTextActive:  { color:BRAND, fontWeight:'700' },
  summaryBox:      { backgroundColor:BRAND_LT, borderRadius:14, padding:14, marginBottom:20 },
  summaryTitle:    { fontSize:15, fontWeight:'700', color:BRAND },
  summarySub:      { fontSize:13, color:'#5B21B6', marginTop:3 },
  fieldLabel:      { fontSize:13, fontWeight:'600', color:GRAY_700, marginBottom:6 },
  fieldHint:       { fontSize:11, color:GRAY_400, marginTop:5 },
  switchRow:       { flexDirection:'row', alignItems:'center', justifyContent:'space-between', gap:12, padding:14, borderRadius:12, borderWidth:1, borderColor:GRAY_200, backgroundColor:GRAY_50 },
  switchTitle:     { fontSize:14, fontWeight:'700', color:GRAY_900 },
  switchSub:       { fontSize:12, color:GRAY_500, marginTop:2, lineHeight:17 },
  authSwitch:      { flexDirection:'row', justifyContent:'center', alignItems:'center', marginTop:20 },
  authSwitchText:  { fontSize:13, color:GRAY_500 },
  authSwitchLink:  { fontSize:13, color:BRAND, fontWeight:'700' },
  input:           { borderWidth:1, borderColor:GRAY_200, borderRadius:12, padding:13, fontSize:15, color:GRAY_900, backgroundColor:'#fff' },
  policyBox:       { backgroundColor:GRAY_50, borderRadius:14, borderWidth:1, borderColor:GRAY_200, padding:14, marginBottom:16 },
  policyTitle:     { fontSize:13, fontWeight:'700', color:GRAY_900, marginBottom:6 },
  policyText:      { fontSize:12, color:GRAY_500, lineHeight:18 },
  policyCheck:     { flexDirection:'row', alignItems:'center', marginTop:12 },
  policyCheckText: { fontSize:13, color:GRAY_700, fontWeight:'500', marginLeft:10, flex:1 },
  doneBox:         { alignItems:'center', paddingTop:40 },
  doneIcon:        { width:72, height:72, borderRadius:36, backgroundColor:BRAND, alignItems:'center', justifyContent:'center', marginBottom:16 },
  doneTitle:       { fontSize:22, fontWeight:'700', color:GRAY_900 },
  doneSub:         { fontSize:14, color:GRAY_500, marginTop:6 },
  doneRef:         { fontSize:12, color:GRAY_400, marginTop:4, fontFamily:Platform.OS==='ios'?'Menlo':'monospace' },
  // Clients
  searchBox:       { flexDirection:'row', alignItems:'center', margin:16, marginBottom:0, padding:12, backgroundColor:GRAY_50, borderRadius:12, borderWidth:1, borderColor:GRAY_200 },
  searchInput:     { flex:1, fontSize:14, color:GRAY_900 },
  msgBtn:          { padding:8 },
  // Messages
  bubble:          { maxWidth:'78%', borderRadius:14, padding:12, marginBottom:8 },
  bubbleLeft:      { backgroundColor:GRAY_100, alignSelf:'flex-start', borderBottomLeftRadius:4 },
  bubbleRight:     { backgroundColor:BRAND, alignSelf:'flex-end', borderBottomRightRadius:4 },
  bubbleText:      { fontSize:14 },
  bubbleTextLeft:  { color:GRAY_900 },
  bubbleTextRight: { color:'#fff' },
  bubbleTime:      { fontSize:10, color:GRAY_400, marginTop:4, alignSelf:'flex-end' },
  composeRow:      { flexDirection:'row', alignItems:'flex-end', padding:12, borderTopWidth:1, borderTopColor:GRAY_100, gap:8, backgroundColor:'#fff' },
  composeInput:    { flex:1, borderWidth:1, borderColor:GRAY_200, borderRadius:20, paddingHorizontal:16, paddingVertical:10, fontSize:14, color:GRAY_900, maxHeight:100 },
  sendBtn:         { width:42, height:42, borderRadius:21, backgroundColor:BRAND, alignItems:'center', justifyContent:'center' },
  unreadDot:       { width:8, height:8, borderRadius:4, backgroundColor:BRAND, marginLeft:6 },
  msgTime:         { fontSize:11, color:GRAY_400 },
  // More
  profileCard:     { flexDirection:'row', alignItems:'center', gap:14, backgroundColor:'#fff', borderRadius:16, borderWidth:1, borderColor:GRAY_100, padding:16, marginBottom:16, shadowColor:'#000', shadowOpacity:0.04, shadowRadius:4, shadowOffset:{width:0,height:1} },
  avatarLg:        { width:52, height:52, borderRadius:26, backgroundColor:BRAND_LT, alignItems:'center', justifyContent:'center' },
  avatarLgText:    { color:BRAND, fontWeight:'700', fontSize:18 },
  profileName:     { fontSize:16, fontWeight:'700', color:GRAY_900 },
  profileRole:     { fontSize:13, color:GRAY_500, textTransform:'capitalize', marginTop:2 },
  menuCard:        { backgroundColor:'#fff', borderRadius:16, borderWidth:1, borderColor:GRAY_100, marginBottom:16, overflow:'hidden', shadowColor:'#000', shadowOpacity:0.04, shadowRadius:4, shadowOffset:{width:0,height:1} },
  menuRow:         { flexDirection:'row', alignItems:'center', padding:16, gap:12 },
  menuRowBorder:   { borderBottomWidth:1, borderBottomColor:GRAY_100 },
  menuIcon:        { width:36, height:36, borderRadius:10, backgroundColor:BRAND_LT, alignItems:'center', justifyContent:'center' },
  menuLabel:       { flex:1, fontSize:15, fontWeight:'500', color:GRAY_900 },
  logoutBtn:       { flexDirection:'row', alignItems:'center', justifyContent:'center', padding:16, backgroundColor:'#FEF2F2', borderRadius:14, borderWidth:1, borderColor:'#FCA5A5' },
  // Login
  loginWrap:       { flex:1, padding:28, justifyContent:'center' },
  loginLogo:       { flexDirection:'row', alignItems:'center', gap:12, marginBottom:32 },
  logoIcon:        { width:48, height:48, borderRadius:14, backgroundColor:BRAND, alignItems:'center', justifyContent:'center' },
  logoText:        { fontSize:24, fontWeight:'800', color:GRAY_900, letterSpacing:-0.5 },
  loginTitle:      { fontSize:28, fontWeight:'800', color:GRAY_900, letterSpacing:-0.5 },
  loginSub:        { fontSize:14, color:GRAY_500, marginTop:4, marginBottom:24 },
  pwToggle:        { position:'absolute', right:14, top:14 },
  // Search
  unreadCount:     { fontSize:11, color:'#fff', backgroundColor:BRAND, borderRadius:99, paddingHorizontal:6, paddingVertical:1, fontWeight:'700' },
});

export const cal = StyleSheet.create({
  topbar:        { flexDirection:'row', alignItems:'center', justifyContent:'space-between', paddingHorizontal:16, paddingVertical:12, borderBottomWidth:1, borderBottomColor:GRAY_100, backgroundColor:'#fff' },
  topBtn:        { width:32, height:32, alignItems:'center', justifyContent:'center' },
  monthWrap:     { flexDirection:'row', alignItems:'center' },
  monthText:     { fontSize:17, fontWeight:'700', color:GRAY_900 },
  filterChip:    { borderWidth:1, borderColor:GRAY_200, borderRadius:999, paddingHorizontal:12, paddingVertical:7, backgroundColor:'#fff' },
  filterChipOn:  { borderColor:BRAND, backgroundColor:BRAND },
  filterText:    { fontSize:12, fontWeight:'700', color:GRAY_500 },
  filterTextOn:  { color:'#fff' },
  dateHeader:    { backgroundColor:GRAY_50, paddingHorizontal:16, paddingVertical:8 },
  dateHeaderToday:{ backgroundColor:'#EFF6FF' },
  dateHeaderText:{ fontSize:12, fontWeight:'700', color:GRAY_500, letterSpacing:0.5 },
  dateHeaderTextToday:{ color:'#2563EB' },
  emptyDay:      { paddingHorizontal:16, paddingVertical:16, color:GRAY_400, fontSize:14 },
  aptRow:        { flexDirection:'row', alignItems:'center', gap:12, paddingHorizontal:16, paddingVertical:14, borderBottomWidth:1, borderBottomColor:GRAY_100, backgroundColor:'#fff' },
  aptBar:        { width:3, height:38, borderRadius:2 },
  aptClient:     { fontSize:15, fontWeight:'700', color:GRAY_900 },
  aptService:    { fontSize:13, color:GRAY_500, marginTop:2 },
  aptTime:       { fontSize:15, fontWeight:'600', color:GRAY_900 },
  aptDur:        { fontSize:13, color:GRAY_500, marginTop:2 },
  stripWrap:     { paddingVertical:10, borderBottomWidth:1, borderBottomColor:GRAY_100, backgroundColor:'#fff' },
  allDay:        { width:52, borderRadius:14, borderWidth:1, borderColor:GRAY_200, backgroundColor:'#fff', alignItems:'center', justifyContent:'center', paddingVertical:8, gap:2 },
  allDayOn:      { backgroundColor:BRAND, borderColor:BRAND },
  allDayText:    { fontSize:11, fontWeight:'700', color:GRAY_500 },
  dayCell:       { width:52, borderRadius:14, borderWidth:1, borderColor:GRAY_200, backgroundColor:'#fff', alignItems:'center', paddingVertical:8 },
  dayCellOn:     { backgroundColor:BRAND, borderColor:BRAND },
  dayDow:        { fontSize:10, fontWeight:'700', color:GRAY_400, letterSpacing:0.4 },
  dayNum:        { fontSize:18, fontWeight:'700', color:GRAY_900, marginTop:2 },
  dayDot:        { width:5, height:5, borderRadius:3, marginTop:4, backgroundColor:'transparent' },
});

// Checkout / Tap to Pay styles
export const co = StyleSheet.create({
  amountArea:   { alignItems:'center', paddingVertical:28 },
  amountLabel:  { fontSize:13, color:GRAY_500, marginBottom:8 },
  amountValue:  { fontSize:48, fontWeight:'800', color:GRAY_900, letterSpacing:-1 },
  amountNote:   { fontSize:13, color:GRAY_500, marginTop:8 },
  pad:          { flexDirection:'row', flexWrap:'wrap', paddingHorizontal:24 },
  key:          { width:'33.33%', height:62, alignItems:'center', justifyContent:'center' },
  keyText:      { fontSize:26, fontWeight:'600', color:GRAY_900 },
  chargeBtn:    { backgroundColor:BRAND, margin:20, marginTop:12, borderRadius:16, paddingVertical:18, alignItems:'center' },
  chargeBtnText:{ color:'#fff', fontSize:17, fontWeight:'700' },
  tipRow:       { flexDirection:'row', alignItems:'center', gap:8, paddingHorizontal:20, marginTop:4 },
  tipLabel:     { fontSize:13, fontWeight:'700', color:GRAY_500, marginRight:2 },
  tipChip:      { paddingHorizontal:14, paddingVertical:8, borderRadius:12, borderWidth:1, borderColor:GRAY_200, backgroundColor:'#fff' },
  tipChipOn:    { backgroundColor:BRAND, borderColor:BRAND },
  tipChipText:  { fontSize:13, fontWeight:'700', color:GRAY_700 },
  tipSummary:   { textAlign:'center', color:GRAY_500, fontSize:13, marginTop:8 },
  // Tap to Pay full-screen
  tapWrap:      { flex:1, alignItems:'center', justifyContent:'center', paddingHorizontal:32 },
  tapAmount:    { color:'#fff', fontSize:40, fontWeight:'800', marginBottom:28 },
  tapNfc:       { width:96, height:96, borderRadius:48, borderWidth:2, borderColor:'rgba(255,255,255,0.4)', alignItems:'center', justifyContent:'center', marginBottom:24 },
  tapTitle:     { color:'#fff', fontSize:22, fontWeight:'700', marginBottom:8 },
  tapSub:       { color:'rgba(255,255,255,0.7)', fontSize:14, textAlign:'center', lineHeight:20 },
  tapDone:      { marginTop:32, backgroundColor:'#fff', paddingVertical:15, borderRadius:14, alignSelf:'stretch', alignItems:'center' },
  tapDoneText:  { color:'#111827', fontWeight:'700', fontSize:16 },
  tapCancel:    { color:'rgba(255,255,255,0.6)', fontSize:14 },
  // Receipt
  receiptWrap:  { flex:1, alignItems:'center', justifyContent:'center', paddingHorizontal:28 },
  receiptCheck: { width:72, height:72, borderRadius:36, backgroundColor:'#10B981', alignItems:'center', justifyContent:'center', marginBottom:20 },
  receiptAmount:{ fontSize:40, fontWeight:'800', color:GRAY_900 },
  receiptPaid:  { fontSize:15, color:GRAY_500, marginTop:4, marginBottom:24 },
  receiptCard:  { alignSelf:'stretch', backgroundColor:'#fff', borderRadius:16, borderWidth:1, borderColor:GRAY_100, paddingVertical:4 },
  receiptRow:   { flexDirection:'row', justifyContent:'space-between', paddingHorizontal:16, paddingVertical:12, borderBottomWidth:1, borderBottomColor:GRAY_50 },
  receiptRowL:  { color:GRAY_500, fontSize:14 },
  receiptRowV:  { color:GRAY_900, fontSize:14, fontWeight:'600' },
});

export const ms = StyleSheet.create({
  row:       { flexDirection:'row', alignItems:'center', gap:12, backgroundColor:'#fff', borderRadius:14, borderWidth:1, borderColor:GRAY_100, padding:14, marginBottom:10 },
  methodChip:  { flex:1, alignItems:'center', paddingVertical:10, borderRadius:12, borderWidth:1, borderColor:GRAY_200 },
  methodChipOn:{ borderColor:BRAND, backgroundColor:BRAND_LT },
  methodChipText:{ fontSize:14, fontWeight:'600', color:GRAY_700 },
  smallAction: { borderWidth:1, borderColor:GRAY_200, borderRadius:10, paddingHorizontal:10, paddingVertical:7 },
  smallActionText:{ fontSize:12, fontWeight:'700', color:GRAY_700 },
  iconAction:  { width:34, height:34, borderRadius:10, alignItems:'center', justifyContent:'center', backgroundColor:'#FEF2F2' },
  checkCircle: { width:26, height:26, borderRadius:13, borderWidth:2, borderColor:GRAY_200, alignItems:'center', justifyContent:'center' },
  checkCircleOn:{ borderColor:'#10B981', backgroundColor:'#10B981' },
  notifRow:    { flexDirection:'row', alignItems:'center', justifyContent:'space-between', paddingVertical:14, paddingHorizontal:4 },
  notifRowBorder:{ borderBottomWidth:1, borderBottomColor:GRAY_50 },
  statusOn:    { flexDirection:'row', alignItems:'center', gap:6 },
  statusDot:   { width:7, height:7, borderRadius:4, backgroundColor:'#10B981' },
  statusOnText:{ fontSize:13, fontWeight:'600', color:'#047857' },
  soonIcon:    { width:60, height:60, borderRadius:30, backgroundColor:BRAND_LT, alignItems:'center', justifyContent:'center' },
  recoveryBox: { marginTop:12, borderWidth:1, borderColor:'#FCD34D', backgroundColor:'#FFFBEB', borderRadius:14, padding:14 },
  recoveryTitle:{ fontSize:14, fontWeight:'700', color:'#92400E' },
  recoverySub: { fontSize:12, color:'#B45309', marginTop:2, marginBottom:10 },
  recoveryGrid:{ flexDirection:'row', flexWrap:'wrap', backgroundColor:'#fff', borderRadius:10, borderWidth:1, borderColor:'#FDE68A', padding:10 },
  recoveryCode:{ width:'50%', fontSize:13, color:GRAY_900, paddingVertical:3, fontVariant:['tabular-nums'] },
  dot:       { width:10, height:10, borderRadius:5 },
  rowTitle:  { fontSize:15, fontWeight:'600', color:GRAY_900 },
  rowMeta:   { fontSize:13, color:GRAY_500, marginTop:2 },
  card:      { backgroundColor:'#fff', borderRadius:14, borderWidth:1, borderColor:GRAY_100, padding:14, marginBottom:10 },
  cardLabel: { fontSize:12, color:GRAY_500 },
  cardValue: { fontSize:16, fontWeight:'700', color:GRAY_900, marginTop:2 },
  empty:     { fontSize:13, color:GRAY_400, textAlign:'center', paddingVertical:12 },
  dealChip:  { backgroundColor:'#D1FAE5', borderRadius:6, paddingHorizontal:8, paddingVertical:3 },
  dealChipText:{ fontSize:12, fontWeight:'700', color:'#065F46' },
});

export const dst = StyleSheet.create({
  chip:      { minWidth:46, alignItems:'center', paddingVertical:8, paddingHorizontal:10, borderRadius:12, borderWidth:1, borderColor:GRAY_200, backgroundColor:'#fff' },
  chipOn:    { backgroundColor:BRAND, borderColor:BRAND },
  chipDow:   { fontSize:11, fontWeight:'700', color:GRAY_500 },
  chipNum:   { fontSize:16, fontWeight:'800', color:GRAY_900, marginTop:2 },
  chipTextOn:{ color:'#fff' },
  chipDot:   { width:5, height:5, borderRadius:3, backgroundColor:BRAND, marginTop:4 },
});
